#!/usr/bin/env bash

# terminate after first line that fails
set -e

function ask {
  while read -e -t 1; do : ; done # absorb previous stdin
  read -p "${1} [y/N] " -r        # perform actual prompt
  if [[ ! $REPLY =~ ^[Yy]$ ]]; then
    exit 1
  fi
}

brew update
echo

brew outdated
echo

ask "Continue?"

brew upgrade
echo

services=`brew services list | grep ' started ' | cut -d' ' -f1`

for service in $services; do
  brew services restart $service
  echo
done

brew cleanup --dry-run
echo

ask "Perform cleanup?"

brew cleanup
echo
