#!/usr/bin/env bash -x

# terminate after first line that fails
set -e

versions=$(bundle list | grep rubocop)

bundle update $@ $(echo "$versions" | awk -F '[ ()]' '{print $4}')

bundle exec rubocop --regenerate-todo
