#!/bin/bash

# Usage:
#
#     gemfile-exec gemfiles/rails4.2.gemfile [command]
#
# Example
#
#     gemfile-exec gemfiles/rails4.2.gemfile rake spec

gemfile=$1
shift

export BUNDLE_GEMFILE="$gemfile"

bundle check || bundle install --path vendor

bundle exec $*
