#!/usr/bin/env ruby

# Borrowed from Jim Garvin
# http://github.com/coderifous/dotfiles/blob/master/bin/git-stats.rb

Authors = []
Format = "%20s %13s %12s %12s %10s\n"
printf(Format, *%w(Author commits files-changed insertions deletions net))

open("| git shortlog -s -n").each do |line|
  Authors << line.sub(/^\s*\d+\s*/, '').chomp
end

Authors.each do |name|
  commits = files_changed = insertions = deletions = 0
  open("| git log --shortstat --no-merges --author='#{name}' | grep 'files changed'").each do |line|
    matchdata = line.match(/(\d+) files changed, (\d+) insertions.* (\d+) deletions/)
    next unless matchdata
    commits       += 1
    files_changed += matchdata[1].to_i
    insertions    += matchdata[2].to_i
    deletions     += matchdata[3].to_i
  end

  printf(Format, name, commits, files_changed, insertions, "-#{deletions}", insertions - deletions) unless commits == 0
end
