#!/usr/bin/env ruby

require "time"
require "date"
require "shellwords"

days_shift = 0
day = Time.parse(Date.today.to_s)

if ARGV[0] == "yesterday"
  days_shift = -1
elsif ARGV[0].to_i <= 0
  days_shift = ARGV[0].to_i
else
  day = Time.parse(ARGV[0])
end

day_in_secs = 24 * 60 * 60
day += days_shift * day_in_secs

after = day
before = (day + day_in_secs)
author = (ARGV[1] || `git config user.email`).chomp

command = ["git-summary", after.iso8601, before.iso8601, author].shelljoin
puts `#{command}`
