#!/usr/bin/env ruby
#
# Starts a mongo shell to MongoDB server specified by a heroku config
#
# Usage:
#   mongo-heroku
#   mongo-heroku --remote production
#   mongo-heroku --app myapp
#
# Inspired by https://github.com/dglittle/mongo-heroku

require "uri"

args = ARGV.join(" ")
config = `heroku config #{args}`
exit 1 unless $?.success?

if config.match(/\b(mongodb:.+)$/)
  db = URI.parse($1)
  exec "mongo -u #{db.user} -p #{db.password} #{db.host}:#{db.port}#{db.path}"
else
  $stderr.puts " !    No MongoDB URL found in heroku config."
  exit 1
end
