#!/bin/sh

if tty -s ; then
  echo
  echo This will rename files in your current directory.  
  echo The prefix \'$1\' will be stripped from every filename 
  echo \(e.g. \'$1sample.txt\' would become \'sample.txt\'\).
  echo
  echo -n "OK to procede? (y or n) ";   read ans
  case "$ans" in y*|Y*)
    ;;
  *)
    echo Quiting...
    exit 0
    ;;
  esac
else
  exit 1
fi

echo

for f in $1?*
do
  echo mv $f `echo $f | sed "s/$1//g" -`
  mv $f `echo $f | sed "s/$1//g" -`
done
