#!/bin/bash

echo

for f in $*
do

  basefilename=`basename $f .svg`
  newfilename=$basefilename.svgz
  echo -n '   ' $f '->' $newfilename
  gzip -c $f > $newfilename

  oldsize=`ls -lh $f | awk '{ print $5; }'`
  newsize=`ls -lh $newfilename | awk '{ print $5; }'`
  echo '   (' $oldsize '->' $newsize ')'

done

echo


